CREATE TABLE events (
id INTEGER PRIMARY KEY,
title TEXT NOT NULL,
date DATETIME NOT NULL,
url TEXT NOT NULL,
venue TEXT NOT NULL,
created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX events_uq_title_date ON events(title, date);

CREATE TABLE venues (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT,
  name TEXT UNIQUE,
  shortname TEXT UNIQUE
);

CREATE TABLE updates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  datetime  DATETIME DEFAULT CURRENT_TIMESTAMP,
  event_id INTEGER NOT NULL,
  field TEXT NOT NULL,
  old TEXT NOT NULL,
  new TEXT NOT NULL
);

CREATE TABLE errors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  datetime  DATETIME DEFAULT CURRENT_TIMESTAMP,
  crawler TEXT NOT NULL,
  msg TEXT NOT NULL
);

CREATE TABLE keyvalue (
  key   TEXT PRIMARY KEY,
  value TEXT
);